[versions]
kotlinStdlib = "1.9.20"
kotlinCoroutinesAndroid = "1.9.0-alpha01"
kotlinCoroutinesGuava = "1.4.0-rc01"
espressoContrib = "1.7.0-rc01"
espressoCore = "1.1.0-alpha04"
testCore = "2.3.0-alpha01"
testExtJunit = "1.1.0-alpha02"
testRunner = "1.3.0-alpha02"
testRules = "1.3.0-alpha05"

[libraries]
#AndroidX
#kotlinStdlib = { module = "androidx.kotlinStdlib", version.ref = "1.10.0-alpha01" }
#kotlinCoroutinesAndroid = { module = "androidx.kotlinCoroutinesAndroid", version.ref = "1.9.0-alpha01" }
#kotlinCoroutinesGuava = { module = "androidx.kotlinCoroutinesGuava", version.ref = "1.4.0-rc01" }
#espressoCore = { module = "androidx.espressoCore", version.ref = "1.1.0-alpha04" }
#testCore = { module = "androidx.testCore", version.ref = "2.3.0-alpha01" }
#testExtJunit = { module = "androidx.testExtJunit", version.ref = "1.1.0-alpha02" }
#testRunner = { module = "androidx.testRunner", version.ref = "1.3.0-alpha02" }
#testRules = { module = "androidx.testRules", version.ref = "1.3.0-alpha05" }

[bundles]
#espressoContrib = { module = "androidx.bundles.espressoContrib", version.ref = "1.7.0-rc01" }


